config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout', :edit => 'profile'},
             :controllers => {:omniauth_callbacks => 'omniauth_callbacks'}
  get 'pages/about'
  root 'project#index'

  resources :project do
    resources :task, only: [:show]
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: [:slugged, :finders]
  has_many :tasks
  validates :name, presence: true, length: {maximum: 50}
  validates :content, presence: true, length: {maximum: 5000}
  validates :price, presence: true, numericality: {only_integer: true}

  mount_uploader :image, ProjectImageUploader

  def shortname
    name.length > 25 ? name[0..25] + "..." : name
  end

end

app/models/task.rb
class Task < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: [:slugged, :finders]

  belongs_to :project

  validates :title, presence: true, length: {maximum: 50}
  validates :video, presence: true
  validates :tag, presence: true
  validates :project, presence: true



end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable
  validates :name, presence: :true, length: {maximum: 25}

  def self.find_for_google_oauth2(access_token, signed_in_resource=nil)
    data = access_token.info
    user = User.where(:provider => access_token.provider, :uid => access_token.uid).first

    if user
      return user
    else
      registered_user = User.where(:email => access_token.email).first
      if registered_user
        return registered_user
      else
        user = User.create(
                       name: data["name"],
                       provider: access_token.provider,
                       email: data["email"],
                       uid: access_token.uid,
                       password: Devise.friendly_token[0,20]
        )
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :password, :remember_me])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name, :email, :password, :remember_me])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :email, :password, :remember_me, :current_password])
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def google_oauth2
    @user = User.find_for_google_oauth2(request.env["omniauth.auth"] ,current_user)

    if @user.persisted?
      flash[:notice] = I18n.t "Devise.omniauth_callbacks.success", :kind => "Google"
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.google_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

app/controllers/project_controller.rb
class ProjectController < ApplicationController
  def index
    @projects = Project.all
  end

  def show
    @project = Project.friendly.find(params[:id])
    @tasks = @project.tasks.order(:tag)

  end
end

app/controllers/task_controller.rb
class TaskController < ApplicationController
  def show
    project = Project.friendly.find(params[:project_id])
    @tasks = project.tasks.order(:tag)
    @task = @tasks.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def avatar_url(user)
    gravatar_id = Digest::MD5::hexdigest(user.email).downcase
    "https://www.gravatar.com/avatar/#{gravatar_id}.jpg?d=identicon&s=40"
  end

  class CodeRayify < Redcarpet::Render::HTML
    def block_code(code, language)
      CodeRay.scan(code, language).div(:line_numbers => :table)
    end
  end

  def markdown(text)
    coderayified = CodeRayify.new(:filter_html => true, :hard_wrap => true)
    options = {
        :fenced_code_blocks => true,
        :no_intra_emphasis => true,
        :autolink => true,
        :strikethrough => true,
        :lax_html_blocks => true,
        :superscript => true
    }

    markdown_to_html = Redcarpet::Markdown.new(coderayified, options)
    markdown_to_html.render(text).html_safe
  end
end

app/helpers/project_helper.rb
module ProjectHelper
end

app/helpers/task_helper.rb
module TaskHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EduCurio</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>

<%= render partial: "shared/header" %>
<%= render partial: "shared/message" %>

<main>
  <div class="container">
    <%= yield %>
  </div>
</main>

<%= render partial: "shared/footer" %>

</body>

<script type="text/javascript" charset="utf-8">
    $(document).ready(function(){
        $('.side-nav').sideNav();
        $(".button-collapse").sideNav();
        $(".dropdown-trigger").dropdown();
    });
</script>
</html>

app/views/pages/about.html.erb
<div class="container">
  <h3>About Me</h3>
  <div class="card z-depth-6">
    <div class="card-content white-text">
      <div class="row">
        <div class="col m6">
          <a class="twitter-timeline" href="https://twitter.com/jAtlas7" data-widget-id="687612111766302720">
            Tweets by @jAtlas7
          </a>
          <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");
          </script>
        </div>
        <div class="col m6">
          <div class="card-panel grey lighten-5 z-depth-1">
            <div class="row valign-wrapper">
              <div class="col m3">
                <%= image_tag "avatar.jpg", class: "circle responsive-img" %>
              </div>
              <div class="col m9">
								<span class="black-text">
									I don't know what to say. Let the world tell you more... :)
								</span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/project/index.html.erb
<div class="row" data-no-turbolink>
  <br/>

  <% @projects.each do |project| %>
    <%= link_to project do %>
      <div class="col s12 m6 l4">
        <div class="card">

          <div class="card-image ">
            <%=  image_tag project.image.url %>
          </div>

          <div class="card-content" style="height: 6em">
						<span class= "card-title grey-text text-darken-4"><%= project.shortname %>
						</span>
          </div>

        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/project/show.html.erb
<div class="row">
  <div class="col m4">
    <div class="card z-depth-2">
      <div class="center">
        <h1>$<%= @project.price  %></h1>
      </div>
      <div class="card-action center">
        <button class="btn waves-effect waves-light pink darken-2">
          Take Project
        </button>
      </div>
    </div>
  </div>

  <div class="col m8">
    <div class="card z-depth-2">
      <div class="card-image">
        <%= image_tag @project.image.url %>
      </div>
      <div class="card-content grey-text text-darken-4">
        <h5><%= @project.name %></h5>
        <hr>
        <%= @project.content %>

        <div class="collection">
          <% @tasks.each do |task| %>
            <% if task.header %>
              <div class="collection-item active">
                <i class="mdi-social-school"> <%= task.title %></i>
              </div>
            <% else %>
              <%= link_to [task.project, task], class: "collection-item" do %>
                <%= task.title %>
              <% end %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_devisemes.html.erb
<% unless resource.errors.empty? %>
  <script type="text/javascript" charset="utf-8">
      <% resource.errors.each do |msg| %>
      toastr.error('<%= msg %>')
      <% end %>
  </script>
<% end %>

app/views/shared/_footer.html.erb
<footer class="page-footer brown lighten-4">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">EduCurio</h5>
        <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer content.</p>
      </div>
      <div class="col l4 offset-l2 s12">
        <h5 class="white-text">Social</h5>
        <ul>
          <li><a class="grey-text text-lighten-3" href="#!">Twitter</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Facebook</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Google Plus</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
      © 2018 Copyright EduCurio
      <%= link_to "About Us ", pages_about_path, class: "grey-text text-lighten-4 right" %>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header>

  <ul id="dropdown1" class="dropdown-content">
    <li><%= link_to "My Profile", edit_user_registration_path %></li>
    <li class="divider"></li>
    <li><a href="#!">My Courses</a></li>
    <li class="divider"></li>
    <li><%= link_to "Log Out", destroy_user_session_path, method: :delete  %></li>
  </ul>
  <ul id="dropdown2" class="dropdown-content">
    <li><%= link_to "My Profile", edit_user_registration_path %></li>
    <li class="divider"></li>
    <li><a href="#!">My Courses</a></li>
    <li class="divider"></li>
    <li><%= link_to "Log Out", destroy_user_session_path, method: :delete  %></li>
  </ul>

  <nav class="brown lighten-4 z-depth-2">
    <div class="container">
      <div class="nav-wrapper">
        <a href="#!" class="brand-logo">EduCurio</a>
        <a href="#" data-target="mobile-demo" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
        <ul class="right hide-on-med-and-down">
          <li><a href="#">Courses</a></li>
          <% unless user_signed_in? %>
            <li><%= link_to "Sign In", new_user_session_path %></li>
            <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <% else %>
            <!-- Dropdown Trigger -->
            <li><a class="dropdown-trigger valign-wrapper" href="" data-activates="dropdown1">
              <%= image_tag avatar_url(current_user), class: "cirle responsive-image" %>&nbsp;
              <%= current_user.name %><i class="material-icons right">arrow_drop_down</i></a>
            </li>
          <% end %>
        </ul>
        <ul class="side-nav" id="mobile-demo">
          <li><a href="#">Courses</a></li>
          <li><a href="#">Courses</a></li>
          <% unless user_signed_in? %>
            <li><%= link_to "Sign In", new_user_session_path %></li>
            <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <% else %>
            <!-- Dropdown Trigger -->
            <li><a class="dropdown-trigger valign-wrapper" href="" data-activates="dropdown2">
              <%= image_tag avatar_url(current_user), class: "cirle responsive-image" %>&nbsp;
              <%= current_user.name %><i class="material-icons right">arrow_drop_down</i></a>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/shared/_message.html.erb
<% unless flash.empty? %>
  <script type="text/javascript" charset="utf-8">
    <% flash.each do |f| %>
      <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
      toastr['<%= type %>']('<%= f[1] %>')
    <% end %>
  </script>
<% end %>

app/views/task/show.html.erb
<div class="row">
  <div class="col m4">
    <div class="card z-depth-2">
      <div class="card-content">
        <div class="collection">
          <% @tasks.each do |task| %>
            <% if task.header %>
              <div class="collection-item active">
                <i class="mdi-social-school"> <%= task.title %> </i>
              </div>
            <% else %>
              <%= link_to [task.project, task], class: "collection-item" do %>
                <%= task.title %>
              <% end %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <div class="col m8">
    <div class="card z-depth-2">
      <div class="card-content">
        <%= @task.video %>
      </div>
      <div class="card-action grey-text text-darken-4">
        <h5><%= @task.title %></h5>
        <hr>
        <%= markdown(@task.note) %>
      </div>
    </div>
  </div>
</div>